{% set name = "torchcam" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchcam-{{ version }}.tar.gz
  sha256: 75e1ad46ad583c1b1bf0165ddf71f94eed18c99f8478d934a9062328c45ed4ef

build:
  number: 1
  noarch: python
  script:
    ## Ensure exclusion of tests folder
    - rm -rf test  # [not win]
    ## Install package {{ name }} from PyPI
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.0.0
    - numpy >=1.14.0
    - pillow >=8.3.2
    - pytorch >=1.5.1

test:
  imports:
    - torchcam
    - torchcam.methods
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/frgfm/torch-cam
  summary: Class activation maps for your PyTorch CNN models
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Simple way to leverage the class-specific activation of 
    convolutional layers in PyTorch.
  doc_url: https://frgfm.github.io/torch-cam
  dev_url: https://github.com/frgfm/torch-cam

extra:
  recipe-maintainers:
    - sugatoray
